apiVersion: v1
kind: Service
metadata:
  name: misc-service-svc
  namespace: wallet-be-dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
  labels:
    k8s-app: misc-service-svc
spec:
  type: LoadBalancer
  selector:
    k8s-app: misc-service
  ports:
  - name: http
    port: 80
    targetPort: 8081

